name: anntibackdoor
version: 1.0
main: anntibackdoor.SupportServer
api-version: 1.16
commands:
  wop:
    description: Quản lý OP whitelist
    usage: /wop <add|remove|reload|list|ban|unban>
    permission: Sunflower.SP.admin