# Thời gian ban (giây), -1 = vĩnh viễn
ban_duration: 120

# Cấu hình chống lạm dụng chế độ Create
Anti_Create_Abuse:
  # Bật/Tắt
  enabled: true
  # Chặn sử dụng lệnh
  block_commands: true
  # Hạn chế di chuyển
  restrict_movement: true
  # Số lần cảnh báo, sau đo kick
  warnings: 10