name: AntiBackDoor
version: 1.0
main: AntiBackDoor.Main_plugin
api-version: 1.16
commands:
  wop:
    description: Quản lý OP whitelist
    usage: /wop <add|remove|reload|list|ban|unban>
    permission: AntiBackDoor.Admin
  info:
    description: thông tin Player
    usage: /info <player>
    permission: AntiBackDoor.Admin

permissions:
  antibackdoor.create:
    description: Cho phép sử dụng chế độ Create
    default: false
  antibackdoor.Admin:
    description: Quyền Admin toàn hệ thống
    default: op